# Using [Annoy](https://github.com/spotify/annoy) for Approximate Nearest Neigbors

Annoy is a convenient tool built by Spotify to build solutions for Approximate Nearest Neighbors.  ANN helps keep inference times quick when building out movie nearest neighbors

In [1]:
from annoy import AnnoyIndex
import pandas as pd

In [2]:
ratings = pd.read_parquet('training_data/movielens_25m_5_5.pq')[['USER_ID', 'MOVIE_ID', 'RATING']]

###  Nearest neighbors based on historical user interactions

In [3]:
util_df=pd.pivot_table(data=ratings,values='RATING',index='USER_ID',columns='MOVIE_ID').fillna(0)
util_df

MOVIE_ID,1,10,100,1000,100001,100008,100015,100017,100032,100034,...,99939,99957,99960,99962,99964,99968,99986,99989,99992,99996
USER_ID,,,,,,,,,,,,,,,,,,,,,
10000,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100016,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100037,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100042,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100045,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99979,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99984,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99985,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99987,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Train the model

In [8]:
from tqdm import tqdm
t = AnnoyIndex(util_df.shape[0], 'angular')
for i in tqdm(util_df):
    v = util_df[i]
    t.add_item(int(i), v)

49753it [29:36, 28.01it/s]

In [9]:
t.build(10) # 10 trees

True

### Save the model for inference later

In [10]:
t.save('movies.ann')

True